 %A script to plot FOLD-FISH data generated by Xiaoze Li
%Wang and analyzed by Nicola Crosetto
%
%Written by Nicola Crosetto in Sep-Nov 2025

%[]{}

cd('/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/FIRST SUBMISSION/Analyses/Image analyses')

%% Plot histogram of nucleus area of all segmented nuclei for all datasets except chr17 datasets

clear all

% Load the .mat file with info about all segmented nuclei
parsed_data_dir = '/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/FIRST SUBMISSION/Analyses/Image analyses/Parsed datasets';
load([parsed_data_dir, '/all_seg_nuc_data.mat']);

% Specify folder where plots should be stored
store_figs_dir = '/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/FIRST SUBMISSION/Analyses/Image analyses/Plots';

% Loop through each dataset and plot histogram of nuc_area in a matrix plot
num_datasets = numel(all_seg_nuc.dataset);

for k = 1:num_datasets
        
    % Plot histogram of nucleus areas for the k-th dataset
    subplot(ceil(num_datasets/3), 3, k); % Create a subplot for each dataset
    [counts, edges] = histcounts(all_seg_nuc.area{k}, 'BinEdges', 25:5:100); % Set bin edges from 25 to 100 with reduced bin width
    hold on;
    % Smoothen the histogram line
    bin_centers = edges(1:end-1) + diff(edges)/2; % Calculate bin centers
    smooth_counts = smoothdata(counts, 'gaussian', 3); % Smooth the counts
    plot(bin_centers, smooth_counts / sum(smooth_counts) * (edges(2) - edges(1)), 'r-', 'LineWidth', 2); % Plot smoothened line
    hold off;
    xlabel('Nucleus Area (um^2)');
    ylabel('Probability Density');
    title(['Dataset: ', all_seg_nuc.dataset{k}], 'Interpreter', 'none');
    xlim([25 100]);
    ylim([0 1]);
    all_seg_nuc_num = numel(all_seg_nuc.area{k}); % Get the number of nuclei
    text(0.95, 0.95, sprintf('n = %d', all_seg_nuc_num), 'Units', 'normalized', ...
        'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontSize', 10);
end

% Adjust layout to prevent overlap
sgtitle('Histogram of Nucleus Area for Each Dataset');
print(gcf, fullfile(store_figs_dir, 'nuc_area_histograms'), '-dpdf');  % Save figure as PDF

close all


%% Plot histograms of dot counts per nucleus for all datasets except chr17 datasets

clear all

% Load all relevant data
parsed_data_dir = '/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/FIRST SUBMISSION/Analyses/Image analyses/Parsed datasets';
files = dir(fullfile(parsed_data_dir, '*__seg_nuc_data.mat'));

load([parsed_data_dir, '/all_seg_nuc_data.mat']); % Load the .mat file with info about all segmented nuclei

% Specify folder where plots should be stored
store_figs_dir = '/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/FIRST SUBMISSION/Analyses/Image analyses/Plots';

% Loop through each dataset and plot dot counts and mean dot contrast per segmented nucleus
for k = 1:numel(files)

    load([parsed_data_dir, '/', files(k).name]); % Load the corresponding .mat file

    %Extract dataset ID and find its index in all_seg_nuc_data.mat
    idx = strfind(files(k).name, '_'); %Find index of underscores
    dataset_id = files(k).name(1:idx(1)-1);
    dataset_idx = find(strcmp(all_seg_nuc.dataset, dataset_id));
   
    % Plot fraction of segmented nuclei with 0,1,2,3,4,>4 dots
    figure(1)
    all_seg_nuc_num = all_seg_nuc.counts(dataset_idx);

    seg_nuc_with_dots_num = numel(seg_nuc_data.dot_counts);
    seg_nuc_1to4dots_num = nnz(seg_nuc_data.dot_counts == 1) + ...
                             nnz(seg_nuc_data.dot_counts == 2) + ...
                             nnz(seg_nuc_data.dot_counts == 3) + ...
                             nnz(seg_nuc_data.dot_counts == 4);

    perc_seg_nuc(1) = (all_seg_nuc_num - seg_nuc_with_dots_num) / (all_seg_nuc_num) * 100; % Fraction of segmented nuclei with 0 dots
    perc_seg_nuc(2) = nnz(seg_nuc_data.dot_counts == 1) / (all_seg_nuc_num) * 100;
    perc_seg_nuc(3) = nnz(seg_nuc_data.dot_counts == 2) / (all_seg_nuc_num) * 100;
    perc_seg_nuc(4) = nnz(seg_nuc_data.dot_counts == 3) / (all_seg_nuc_num) * 100;
    perc_seg_nuc(5) = nnz(seg_nuc_data.dot_counts == 4) / (all_seg_nuc_num) * 100;
    perc_seg_nuc(6) = nnz(seg_nuc_data.dot_counts > 4) / (all_seg_nuc_num) * 100;
    bar(perc_seg_nuc);
    xlabel('# of dots');
    ylabel('% of nuclei');
    title(files(k).name,'interpreter', 'none');
    set(gca, 'XTickLabel', {'0', '1', '2', '3', '4', '>4'});
    text(0.95, 0.95, sprintf('# of segm nuclei: %d', all_seg_nuc_num), 'Units', 'normalized', ...
        'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontSize', 10);
    text(0.95, 0.90, sprintf('# of nuclei with 1-4 dots: %d', seg_nuc_1to4dots_num), 'Units', 'normalized', ...
        'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontSize', 10);
    baseFileName = erase(files(k).name, '.mat');    % Remove .mat from file name for saving figures
    print(figure(1), fullfile(store_figs_dir, [baseFileName,'_dot_counts']), '-dpdf');  % Save figure as PDF

    % Plot histogram of dots per nucleus in segmented nuclei with >= 1 dot
    figure(2)
    histogram(seg_nuc_data.dot_counts, 'Normalization', 'pdf'); % Use 'pdf' to get the density
    xlabel('# of dots per nucleus');
    ylabel('Probability');
    title(files(k).name,'interpreter', 'none');
    xlim([0 12]); % Fix x-axis to maximum 12 dots
    print(figure(2), fullfile(store_figs_dir, [baseFileName,'_dot_histogram']), '-dpdf');  % Save figure as PDF

    close all
    
end


%% Plot histogram of dot SNB values for selected datasets

clear all

% Load all relevant data
source_data_dir = '/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/FIRST SUBMISSION/Analyses/Image analyses/Source datasets/Dot tables';
files = dir(fullfile(source_data_dir, '*__seg_nuc_data.mat'));

% Specify folder where plots should be stored
store_figs_dir = '/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/FIRST SUBMISSION/Analyses/Image analyses/Plots';

datasets={'iiXZ0215_20231221_008_dots_20250904.tsv',...
          'iiXZ1234_20250624_001_dw_800_dots_20250915.tsv',...
          'iiXZ1234_20250624_001_dw_A488_cwdots_20251002.tsv',...
          'iiXZ1234_20250624_001_dw_A488_dots_20250915.tsv',...
          'iiXZ1234_20250624_001_dw_A594_dots_20250915.tsv',...
          'iiXZ1234_20250624_001_dw_A647_dots_20250915.tsv',...
          'iiXZ1234_20250624_001_dw_SpGold_dots_20250915.tsv'};

for k=1:numel(datasets)

    data = readtable([source_data_dir,'/',datasets{k}],'FileType','text');
    
    % Extract contrast of dots in segmented nuclei
    seg_nuc_dot_contr{k} = data.Contrast(data.nuc_id>0);

    % Plot histogram of dot contrasts in segmented nuclei
    figure(1)
    histogram(seg_nuc_dot_contr{k}, 'Normalization', 'pdf'); % Use 'pdf' to get the density
    median_value = median(seg_nuc_dot_contr{k});
    text(0.95, 0.95, sprintf('Median: %.4f', median_value), 'Units', 'normalized', ...
         'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontSize', 10);
    text(0.95, 0.90, sprintf('N: %d', numel(seg_nuc_dot_contr{k})), 'Units', 'normalized', ...
         'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontSize', 10);
    xlabel('Signal-to-background');
    ylabel('Probability Density');
    title(datasets{k}, 'Interpreter', 'none');
    xlim([0.6 1]); % Set x-axis limits based on data range
    print(figure(1), fullfile(store_figs_dir, [datasets{k}(1:end-4), '_contrast_histogram']), '-dpdf');  % Save figure as PDF
    
    figure(2)
    % Plot density line of dot contrasts in segmented nuclei
    [f, xi] = ksdensity(seg_nuc_dot_contr{k}); % Estimate the density
    plot(xi, f, 'LineWidth', 2); % Plot the density line
    xlabel('Signal-to-background');
    ylabel('Probability Density');
    title(datasets{k}, 'Interpreter', 'none');
    xlim([0 1]); % Set x-axis limits based on data range
    print(figure(2), fullfile(store_figs_dir, [datasets{k}(1:end-4), '_contrast_density']), '-dpdf');  % Save figure as PDF

    close all

end


%% Plot data for Suppl Fig 1 in FOLD-FISH manuscript (Sep2025)
% Plot dot contrasts in FOLD-FISH optimization experiments
source_data_dir = '/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/FIRST SUBMISSION/Analyses/Image analyses/Source datasets/Dot tables';

%Specify folder where figures should be stored
store_figs_dir = '/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/FIRST SUBMISSION/Analyses/Image analyses/Plots';


datasets={'iXZ0139_20210309_001_dw_Cy5_dots_20250915.tsv',...
          'iXZ0141_20210309_001_dw_Cy5_dots_20250919.tsv',...
          'iXZ0142_20210309_001_dw_Cy5_dots_20250915.tsv',...
          'iXZ0144_20210309_001_dw_Cy5_dots_20250915.tsv'};

for k=1:numel(datasets)
    
    data = readtable([source_data_dir,'/',datasets{k}],'FileType','text');

    % Extract contrast of dots in segmented nuclei
    seg_nuc_dot_contr{k} = data.Contrast(data.nuc_id>0);

end

%Store dot contrasts in a matrix
max_length = max(cellfun(@numel, seg_nuc_dot_contr));
dot_contrast_matrix = NaN(max_length, numel(datasets));
for k = 1:numel(datasets)
    current_length = numel(seg_nuc_dot_contr{k});
    dot_contrast_matrix(1:current_length, k) = seg_nuc_dot_contr{k};
end

% Plot dot contrast matrix as a boxplot
figure(4)
boxplot(dot_contrast_matrix, 'Labels', datasets, 'OutlierSize', 3, 'Symbol', 'o', 'Color', [0.5 0.5 0.5], 'Jitter', 0.5);
xlabel('Datasets');
ylabel('Dot Contrast');
title('Boxplot of Dot Contrast Across Datasets');
grid on;

% Add median and number of data points as text labels on the boxplot
medians = nanmedian(dot_contrast_matrix);
num_points = sum(~isnan(dot_contrast_matrix));
for k = 1:numel(datasets)
    text(k, medians(k), sprintf('Median: %.4f\nN: %d', medians(k), num_points(k)), ...
        'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom', 'FontSize', 8);
end
print(figure(4), fullfile(store_figs_dir, 'iXZ139_141_142_144_dot_contrast_boxplots'), '-dpdf');  % Save figure as PDF

close all

%% Plot data for Suppl Fig 2 in FOLD-FISH manuscript (Sep2025)
% Plot dot contrasts in FOLD-FISH optimization experiments
source_data_dir = '/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/FIRST SUBMISSION/Analyses/Image analyses/Source datasets/Dot tables';

%Specify folder where figures should be stored
store_figs_dir = '/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/FIRST SUBMISSION/Analyses/Image analyses/Plots';


datasets={'iiXZ0959_20240813_001_100x_dw_A594_dots_20250915.tsv',...
          'iiXZ0960_20240819_001_100x_dw_A594_dots_20250915.tsv',...
          'iiXZ0961 100x_20240814_001_100x_dw_A594_dots_20250915.tsv',...
          'iiXZ0962_20240812_001_100x_dw_A594_dots_20250915.tsv'};

for k=1:numel(datasets)
    
    data = readtable([source_data_dir,'/',datasets{k}],'FileType','text');

    % Extract contrast of dots in segmented nuclei
    seg_nuc_dot_contr{k} = data.Contrast(data.nuc_id>0);

end

%Store dot contrasts in a matrix
max_length = max(cellfun(@numel, seg_nuc_dot_contr));
dot_contrast_matrix = NaN(max_length, numel(datasets));
for k = 1:numel(datasets)
    current_length = numel(seg_nuc_dot_contr{k});
    dot_contrast_matrix(1:current_length, k) = seg_nuc_dot_contr{k};
end

% Plot dot contrast matrix as a boxplot
figure(5)
boxplot(dot_contrast_matrix, 'Labels', datasets, 'OutlierSize', 3, 'Symbol', 'o', 'Color', [0.5 0.5 0.5], 'Jitter', 0.5);
xlabel('Datasets');
ylabel('Dot Contrast');
title('Boxplot of Dot Contrast Across Datasets');
grid on;

% Add median and number of data points as text labels on the boxplot
medians = nanmedian(dot_contrast_matrix);
num_points = sum(~isnan(dot_contrast_matrix));
for k = 1:numel(datasets)
    text(k, medians(k), sprintf('Median: %.4f\nN: %d', medians(k), num_points(k)), ...
        'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom', 'FontSize', 8);
end
print(figure(5), fullfile(store_figs_dir, 'iXZ959_960_961_962_dot_contrast_boxplots'), '-dpdf');  % Save figure as PDF

close all


%% Calculate and plot various properties of chr17 CTs for iiXZ1126 dataset

clear all

%Specify dataset to analyse
dataset_name = 'iiXZ1126_20250210_002_dw_A594_A647_cwdots_clusters_20251013';

%Specify folder where figures should be stored
store_figs_dir = '/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/FIRST SUBMISSION/Analyses/Image analyses/Plots';

% Load the .mat files with info about chr17 clusters
parsed_data_dir = '/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH//FIRST SUBMISSION/Analyses/Image analyses/Parsed datasets';
load([parsed_data_dir, '/', dataset_name, '__seg_nuc_data.mat']);

seg_nuc_num = seg_nuc_data.seg_nuc_num; % # of segmented nuclei with dots in either A594 or A647 or both channels

a594_clust_num = 1; % Counter of A594 clusters with > 4 dots (min required to calculate the cluster convex hull)
a594_seg_nuc_2clust_num = 1; % Counter of nuclei with 2 A594 clusters with > 4 dots

a647_clust_num = 1; % Counter of A647 clusters with > 4 dots (min required to calculate the cluster convex hull)
a647_seg_nuc_2clust_num = 1; % Counter of nuclei with 2 A647 clusters with > 4 dots

%Loop through nuclei, count number of clusters and calculate convex hull volume of each cluster in each channel
for i= 1:seg_nuc_num
    
    %A594 dots
    if seg_nuc_data.a594_dot_counts(i) > 0 %Check if i-th nucleus contains dots in A594
        a594_seg_nuc_clust_num(i,1) = max(seg_nuc_data.a594_cluster_id(seg_nuc_data.a594_nuc_id == i)); % # of A594 clusters in i-th nucleus

        %Calculate convex hull volume (in um^3) of clusters with > 3 dots in each channel
        if a594_seg_nuc_clust_num(i,1) > 0
            for j = 1:a594_seg_nuc_clust_num(i,1)
                a594_dot_in_clust_coord = seg_nuc_data.a594_dot_coord(seg_nuc_data.a594_nuc_id == i & seg_nuc_data.a594_cluster_id == j,1:3);
                if height(a594_dot_in_clust_coord) > 3
                    [~,a594_clust_hull_vol(a594_clust_num,1)] = convhulln(a594_dot_in_clust_coord); % Calculate convex hull volume
                    a594_clust_num = a594_clust_num + 1;
                end
            end
        end

        %Calculate difference in convex hull vol between clusters for nuclei with 2 clusters
        if a594_seg_nuc_clust_num(i,1) == 2
            a594_clust1_dot_coord = seg_nuc_data.a594_dot_coord(seg_nuc_data.a594_nuc_id == i & seg_nuc_data.a594_cluster_id == 1,1:3);
            a594_clust2_dot_coord = seg_nuc_data.a594_dot_coord(seg_nuc_data.a594_nuc_id == i & seg_nuc_data.a594_cluster_id == 2,1:3);
            if height(a594_clust1_dot_coord) > 3 && height(a594_clust2_dot_coord) > 3
                [~,a594_clust1_hull_vol] = convhulln(a594_clust1_dot_coord); % Convex hull volume of cluster 1
                [~,a594_clust2_hull_vol] = convhulln(a594_clust2_dot_coord); % Convex hull volume of cluster 2
                a594_delta_clust_vol(a594_seg_nuc_2clust_num,1) = abs(a594_clust1_hull_vol - a594_clust2_hull_vol) / max(a594_clust1_hull_vol, a594_clust2_hull_vol); % Relative absolute difference in convex hull volume
                a594_seg_nuc_2clust_num = a594_seg_nuc_2clust_num + 1;
            end
        end

    end

    %A647 dots
    if seg_nuc_data.a647_dot_counts(i) > 0 % Check if i-th nucleus contains dots in A647
        a647_seg_nuc_clust_num(i,1) = max(seg_nuc_data.a647_cluster_id(seg_nuc_data.a647_nuc_id == i)); % # of A647 clusters in i-th nucleus

        % Calculate convex hull volume of clusters with > 3 dots in each channel
        if a647_seg_nuc_clust_num(i,1) > 0
            for j = 1:a647_seg_nuc_clust_num(i,1)
                a647_dot_in_clust_coord = seg_nuc_data.a647_dot_coord(seg_nuc_data.a647_nuc_id == i & seg_nuc_data.a647_cluster_id == j,1:3);
                if height(a647_dot_in_clust_coord) > 3
                    [~,a647_clust_hull_vol(a647_clust_num,1)] = convhulln(a647_dot_in_clust_coord); % Calculate convex hull volume
                    a647_clust_num = a647_clust_num + 1;
                end
            end
        end

        % Calculate difference in convex hull vol between clusters for nuclei with 2 clusters
        if a647_seg_nuc_clust_num(i,1) == 2
            a647_clust1_dot_coord = seg_nuc_data.a647_dot_coord(seg_nuc_data.a647_nuc_id == i & seg_nuc_data.a647_cluster_id == 1,1:3);
            a647_clust2_dot_coord = seg_nuc_data.a647_dot_coord(seg_nuc_data.a647_nuc_id == i & seg_nuc_data.a647_cluster_id == 2,1:3);
            if height(a647_clust1_dot_coord) > 3 && height(a647_clust2_dot_coord) > 3
                [~,a647_clust1_hull_vol] = convhulln(a647_clust1_dot_coord); % Convex hull volume of cluster 1
                [~,a647_clust2_hull_vol] = convhulln(a647_clust2_dot_coord); % Convex hull volume of cluster 2
                a647_delta_clust_vol(a647_seg_nuc_2clust_num,1) = abs(a647_clust1_hull_vol - a647_clust2_hull_vol) / max(a647_clust1_hull_vol, a647_clust2_hull_vol); % Relative absolute difference in convex hull volume
                a647_seg_nuc_2clust_num = a647_seg_nuc_2clust_num + 1;
            end
        end
    end

end

%A594 dots
% Plot histogram of number of A594 clusters per nucleus
figure(1);
histogram(a594_seg_nuc_clust_num, 'BinMethod', 'integers', 'FaceColor', [0.7 0.7 0.7], 'Normalization', 'probability');
xlabel('# of clusters per nucleus');
ylabel('Relative Frequency');
text('Position', [0.95, 0.95], 'String', sprintf('n = %d', numel(a594_seg_nuc_clust_num)), ...
    'Units', 'normalized', 'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontSize', 10, 'FontWeight', 'bold');
print(figure(1), fullfile(store_figs_dir, [dataset_name, '__a594_clusters_per_nucleus_histogram']), '-dpdf');  % Save figure as PDF

% Plot boxplot of convex hull volumes of A594 clusters
figure(2);
boxplot(a594_clust_hull_vol, 'OutlierSize', 3, 'Symbol', 'o', 'Color', [0.5 0.5 0.5], 'Jitter', 0.5);
xlabel('Cluster Hull Volume (um^3)');
ylabel('Frequency');
median_volume = nanmedian(a594_clust_hull_vol);
num_clusters = sum(~isnan(a594_clust_hull_vol));
text(1, median_volume, sprintf('Median: %.4f\nN: %d', median_volume, num_clusters), ...
    'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom', 'FontSize', 8);
print(figure(2), fullfile(store_figs_dir, [dataset_name, '__a594_cluster_vol_boxplot']), '-dpdf');  % Save figure as PDF

% Plot boxplot of relative absolute differences in convex hull volume for nuclei with 2 A594 clusters
figure(3);
boxplot(a594_delta_clust_vol, 'OutlierSize', 3, 'Symbol', 'o', 'Color', [0.5 0.5 0.5]);
hold on
scatter_width = 0.9 + (1.1 - 0.9) * rand(1, numel(a594_delta_clust_vol));
scatter(scatter_width, a594_delta_clust_vol);
hold off
ylabel('Relative Difference in Convex Hull Volume');
text('Position', [0.95, 0.95], 'String', sprintf('n = %d', a594_seg_nuc_2clust_num-1), ...
    'Units', 'normalized', 'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontSize', 10, 'FontWeight', 'bold');
print(figure(3), fullfile(store_figs_dir, [dataset_name, '__a594_delta_clust_vol_boxplot']), '-dpdf');  % Save figure as PDF

%A647 dots
% Plot histogram of number of A647 clusters per nucleus
figure(4);
histogram(a647_seg_nuc_clust_num, 'BinMethod', 'integers', 'FaceColor', [0.7 0.7 0.7], 'Normalization', 'probability');
xlabel('# of clusters per nucleus');
ylabel('Frequency');
text('Position', [0.95, 0.95], 'String', sprintf('n = %d', numel(a647_seg_nuc_clust_num)), ...
    'Units', 'normalized', 'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontSize', 10, 'FontWeight', 'bold');
print(figure(4), fullfile(store_figs_dir, [dataset_name, '__a647_clusters_per_nucleus_histogram']), '-dpdf');  % Save figure as PDF

% Plot boxplot of convex hull volumes of A647 clusters
figure(5);
boxplot(a647_clust_hull_vol, 'OutlierSize', 3, 'Symbol', 'o', 'Color', [0.5 0.5 0.5], 'Jitter', 0.5);
xlabel('Cluster Hull Volume (um^3)');
ylabel('Frequency');
median_volume = nanmedian(a647_clust_hull_vol);
num_clusters = sum(~isnan(a647_clust_hull_vol));
text(1, median_volume, sprintf('Median: %.4f\nN: %d', median_volume, num_clusters), ...
    'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom', 'FontSize', 8);
print(figure(5), fullfile(store_figs_dir, [dataset_name, '__a647_cluster_vol_boxplot']), '-dpdf');  % Save figure as PDF

% Plot boxplot of relative absolute differences in convex hull volume for nuclei with 2 A647 clusters
figure(6);
boxplot(a647_delta_clust_vol, 'OutlierSize', 3, 'Symbol', 'o', 'Color', [0.5 0.5 0.5]);
hold on
scatter_width = 0.9 + (1.1 - 0.9) * rand(1, numel(a647_delta_clust_vol));
scatter(scatter_width, a647_delta_clust_vol);
hold off
ylabel('Relative Difference in Convex Hull Volume');
text('Position', [0.95, 0.95], 'String', sprintf('n = %d', a647_seg_nuc_2clust_num-1), ...
    'Units', 'normalized', 'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontSize', 10, 'FontWeight', 'bold');
print(figure(6), fullfile(store_figs_dir, [dataset_name, '__a647_delta_clust_vol_boxplot']), '-dpdf');  % Save figure as PDF



%% Calculate and plot various properties of chr17 CTs for iiXZ1081 dataset

clear all

%Specify dataset to analyse
dataset_name = 'iiXZ1081_20241128_002_dw_A594_cwdots_clusters_20251022';

%Specify folder where figures should be stored
store_figs_dir = '/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/FIRST SUBMISSION/Analyses/Image analyses/Plots/Chr17 territories';

% Load the .mat files with info about chr17 clusters
parsed_data_dir = '/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/FIRST SUBMISSION/Analyses/Image analyses/Parsed datasets';
load([parsed_data_dir, '/', dataset_name, '__seg_nuc_data.mat']);

seg_nuc_num = seg_nuc_data.seg_nuc_num; % # of segmented nuclei with dots in either A594 or A647 or both channels

clust_num = 1; % Counter of clusters
min4dots_clust_num = 1; % Counter of clusters with at least 3 dots (min required to calculate a 3D convex hull)
seg_nuc_2clust_num = 1; % Counter of nuclei with 2 clusters with at least 3 dots


%Loop through nuclei, count number of clusters and calculate convex hull volume of each cluster in each channel
for i= 1:seg_nuc_num
    
    seg_nuc_clust_num(i,1) = max(seg_nuc_data.cluster_id(seg_nuc_data.nuc_id == i)); % # of clusters in i-th nucleus

    %Calculate convex hull volume of clusters with at least 4 dots
    if seg_nuc_clust_num(i,1) > 0
        for j = 1:seg_nuc_clust_num(i,1)
            dot_in_clust_coord = seg_nuc_data.dot_coord(seg_nuc_data.nuc_id == i & seg_nuc_data.cluster_id == j,1:3);
            dot_in_clust_num(clust_num, 1) = height(dot_in_clust_coord);
            if dot_in_clust_num(clust_num, 1) > 3
                [~,clust_hull_vol(min4dots_clust_num,1)] = convhulln(dot_in_clust_coord); % Calculate convex hull volume
                min4dot_in_clust_num(min4dots_clust_num,1) = dot_in_clust_num(clust_num, 1);
                min4dots_clust_num = min4dots_clust_num + 1;
            end
            clust_num = clust_num + 1;
        end
    end

    %Calculate difference in convex hull vol between clusters for nuclei with 2 clusters with at least 4 dots
    if seg_nuc_clust_num(i,1) == 2
        clust1_dot_coord = seg_nuc_data.dot_coord(seg_nuc_data.nuc_id == i & seg_nuc_data.cluster_id == 1,1:3);
        clust2_dot_coord = seg_nuc_data.dot_coord(seg_nuc_data.nuc_id == i & seg_nuc_data.cluster_id == 2,1:3);
        if height(clust1_dot_coord) > 3 && height(clust2_dot_coord) > 3
            [~,clust1_hull_vol(seg_nuc_2clust_num,1)] = convhulln(clust1_dot_coord); % Convex hull volume of cluster 1
            [~,clust2_hull_vol(seg_nuc_2clust_num,1)] = convhulln(clust2_dot_coord); % Convex hull volume of cluster 2
            delta_clust_vol(seg_nuc_2clust_num,1) = abs(clust1_hull_vol(seg_nuc_2clust_num,1) - clust2_hull_vol(seg_nuc_2clust_num,1)) / ...
                                                    max(clust1_hull_vol(seg_nuc_2clust_num,1), clust2_hull_vol(seg_nuc_2clust_num,1)); % Relative absolute difference in convex hull volume
            seg_nuc_2clust_num = seg_nuc_2clust_num + 1;
        end
    end

end

% Plot histogram of number of clusters per nucleus
figure(1);
histogram(seg_nuc_clust_num, 'BinMethod', 'integers', 'FaceColor', [0.7 0.7 0.7], 'Normalization', 'probability');
xlabel('# of clusters per nucleus');
ylabel('Relative Frequency (%)');
text('Position', [0.95, 0.95], 'String', sprintf('n = %d', numel(seg_nuc_clust_num)), ...
    'Units', 'normalized', 'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontSize', 10, 'FontWeight', 'bold');
yticks(0:0.1:1); % Set y-ticks from 0 to 1
yticklabels(0:10:100); % Convert y-tick labels to percentages
print(figure(1), fullfile(store_figs_dir, [dataset_name, '__clusters_per_nucleus_histogram']), '-dpdf');  % Save figure as PDF

% Plot histogram of number of dots in each cluster
figure(2);
histogram(dot_in_clust_num, 'BinMethod', 'integers', 'FaceColor', [0.7 0.7 0.7], 'Normalization', 'probability');
xlabel('# of dots per cluster');
ylabel('Relative Frequency (%)');
text('Position', [0.95, 0.95], 'String', sprintf('n = %d', numel(dot_in_clust_num)), ...
    'Units', 'normalized', 'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontSize', 10, 'FontWeight', 'bold');
yticks(0:0.05:1); % Set y-ticks from 0 to 1 with more ticks
yticklabels(0:5:100); % Convert y-tick labels to percentages
print(figure(2), fullfile(store_figs_dir, [dataset_name, '__dots_per_cluster_histogram']), '-dpdf');  % Save figure as PDF

% Plot histogram of number of dots in each cluster with at least 4 dots
figure(3);
histogram(min4dot_in_clust_num, 'BinMethod', 'integers', 'FaceColor', [0.7 0.7 0.7], 'Normalization', 'probability');
xlabel('# of dots per cluster');
ylabel('Relative Frequency (%)');
text('Position', [0.95, 0.95], 'String', sprintf('n = %d', numel(min4dot_in_clust_num)), ...
    'Units', 'normalized', 'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontSize', 10, 'FontWeight', 'bold');
yticks(0:0.05:1); % Set y-ticks from 0 to 1 with more ticks
yticklabels(0:5:100); % Convert y-tick labels to percentages
print(figure(2), fullfile(store_figs_dir, [dataset_name, '__dots_per_cluster_histogram']), '-dpdf');  % Save figure as PDF

% Plot boxplot of convex hull volumes of clusters with at least 4 dots
figure(4);
boxplot(clust_hull_vol, 'OutlierSize', 3, 'Symbol', 'o', 'Color', [0.5 0.5 0.5], 'Jitter', 0.5);
ylabel('Cluster Hull Volume (um^3)');
median_volume = nanmedian(clust_hull_vol); % Calculate median volume
num_clusters = sum(~isnan(clust_hull_vol));
text(1, median_volume, sprintf('Median: %.4f\nN: %d', median_volume, num_clusters), ...
    'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom', 'FontSize', 8);
print(figure(3), fullfile(store_figs_dir, [dataset_name, '__cluster_vol_boxplot']), '-dpdf');  % Save figure as PDF

% Plot boxplot of relative absolute differences in convex hull volume for nuclei with 2 clusters
figure(5);
boxplot(delta_clust_vol, 'OutlierSize', 3, 'Symbol', 'o', 'Color', [0.5 0.5 0.5]);
hold on
scatter_width = 0.9 + (1.1 - 0.9) * rand(1, numel(delta_clust_vol));
scatter(scatter_width, delta_clust_vol);
hold off
ylabel('Relative Difference in Convex Hull Volume');
text('Position', [0.95, 0.95], 'String', sprintf('n = %d', seg_nuc_2clust_num-1), ...
    'Units', 'normalized', 'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontSize', 10, 'FontWeight', 'bold');
print(figure(4), fullfile(store_figs_dir, [dataset_name, '__delta_clust_vol_boxplot']), '-dpdf');  % Save figure as PDF

% Scatter plot of cluster 1 vs cluster 2 volume
figure(6);
scatter(clust1_hull_vol, clust2_hull_vol, 'filled', 'MarkerFaceColor', [0.7 0.7 0.7]);
xlabel('Cluster #1 Volume');
ylabel('Cluster #2 Volume');
print(figure(6), fullfile(store_figs_dir, [dataset_name, '__scatter_cluster_volumes']), '-dpdf');  % Save figure as PDF

%% Calculate pairwise distances between chr17 p- and q-arm CTs for iiXZ1126 dataset

clear all

%Specify dataset to analyse
dataset_name = 'iiXZ1126_20250210_002_dw_A594_A647_cwdots_clusters_20251013';

%Specify folder where figures should be stored
store_figs_dir = '/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/FIRST SUBMISSION/Analyses/Image analyses/Plots/Chr17 territories';

% Load the .mat files with info about chr17 clusters
parsed_data_dir = '/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/FIRST SUBMISSION/Analyses/Image analyses/Parsed datasets';
load([parsed_data_dir, '/', dataset_name, '__seg_nuc_data.mat']);

seg_nuc_num = seg_nuc_data.seg_nuc_num; % # of segmented nuclei with dots in either A594 or A647 or both channels

n = 1; %Counter of nuclei with 2 clusters in A594 and 2 in A647 and at least 2 dots per cluster
all_a594_intra_clust_pdist = [];
all_a647_intra_clust_pdist = [];

%Loop through nuclei, count number of clusters and calculate pairwise distances between clusters for cells with 2 A594 and 2 A647 clusters
for i= 1:seg_nuc_num
    
    if seg_nuc_data.a594_dot_counts(i) > 0 && seg_nuc_data.a647_dot_counts(i) > 0 %Check if i-th nucleus contains dots in A594 and A647
        a594_seg_nuc_clust_num(i,1) = max(seg_nuc_data.a594_cluster_id(seg_nuc_data.a594_nuc_id == i)); % # of A594 clusters in i-th nucleus
        a647_seg_nuc_clust_num(i,1) = max(seg_nuc_data.a647_cluster_id(seg_nuc_data.a647_nuc_id == i)); % # of A647 clusters in i-th nucleus
        
        %Calculate pairwise distances within and between clusters for nuclei with 2 clusters
        if a594_seg_nuc_clust_num(i,1) == 2 && a647_seg_nuc_clust_num(i,1) == 2
            
            %Extract dot coord in each cluster
            a594_clust1_dot_coord = seg_nuc_data.a594_dot_coord(seg_nuc_data.a594_nuc_id == i & seg_nuc_data.a594_cluster_id == 1,1:3);
            a594_clust2_dot_coord = seg_nuc_data.a594_dot_coord(seg_nuc_data.a594_nuc_id == i & seg_nuc_data.a594_cluster_id == 2,1:3);          
            a647_clust1_dot_coord = seg_nuc_data.a647_dot_coord(seg_nuc_data.a647_nuc_id == i & seg_nuc_data.a647_cluster_id == 1,1:3);
            a647_clust2_dot_coord = seg_nuc_data.a647_dot_coord(seg_nuc_data.a647_nuc_id == i & seg_nuc_data.a647_cluster_id == 2,1:3);

            %Check that each cluster contains at least 2 dots
            if height(a594_clust1_dot_coord)>1 && height(a594_clust2_dot_coord)>1 && height(a647_clust1_dot_coord)>1 && height(a647_clust2_dot_coord)>1

                %Calculate centroid coord in each cluster
                a594_clust1_centroid_coord = mean(a594_clust1_dot_coord);
                a594_clust2_centroid_coord = mean(a594_clust2_dot_coord);
                a647_clust1_centroid_coord = mean(a647_clust1_dot_coord);
                a647_clust2_centroid_coord = mean(a647_clust2_dot_coord);

                %Calculate intra-cluster pdist
                a594_pdist = vertcat(pdist(a594_clust1_dot_coord)', pdist(a594_clust2_dot_coord)');
                a647_pdist = vertcat(pdist(a647_clust1_dot_coord)', pdist(a647_clust2_dot_coord)');
                mean_a594_pdist(n,1) = mean(a594_pdist);
                mean_a647_pdist(n,1) = mean(a647_pdist);
                all_a594_intra_clust_pdist = vertcat(all_a594_intra_clust_pdist,a594_pdist);
                all_a647_intra_clust_pdist = vertcat(all_a647_intra_clust_pdist, a647_pdist);

                %Calculate inter-centroid dist
                a594_inter_centroid_dist(n,1) = pdist2(a594_clust1_centroid_coord,a594_clust2_centroid_coord);
                a647_inter_centroid_dist(n,1) = pdist2(a647_clust1_centroid_coord,a647_clust2_centroid_coord);
                min_a594_a647_inter_centroid_dist(n,1) = min(vertcat(pdist2(a594_clust1_centroid_coord,a647_clust1_centroid_coord),...
                    pdist2(a594_clust1_centroid_coord,a647_clust2_centroid_coord),...
                    pdist2(a594_clust2_centroid_coord,a647_clust1_centroid_coord),...
                    pdist2(a594_clust2_centroid_coord,a647_clust2_centroid_coord)));

                n = n + 1; % Increment counter of nuclei with 2 clusters in A594 and 2 in A647

            end
            
        end

    end

end

% Plot dot plots of intra- and inter-cluster distances
figure(1);
subplot(3, 2, 1);
scatter(0.8 + 0.4 * rand(size(mean_a594_pdist)), mean_a594_pdist, 'filled', 'MarkerFaceColor', [0.7 0.7 0.7], 'SizeData', 7); % Make dots smaller
xlim([0 2]); % Set x-axis limits
ylabel('A594 Pairwise Distance');
text('Position', [0.95, 0.95], 'String', sprintf('n = %d\nMedian: %.4f', numel(mean_a594_pdist), nanmedian(mean_a594_pdist)), ...
    'Units', 'normalized', 'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontSize', 10, 'FontWeight', 'bold');
hold on;
yline(nanmedian(mean_a594_pdist), 'r--', 'Median', 'LabelHorizontalAlignment', 'left'); % Add median line
hold off;

subplot(3, 2, 2);
scatter(0.8 + 0.4 * rand(size(mean_a647_pdist)), mean_a647_pdist, 'filled', 'MarkerFaceColor', [0.7 0.7 0.7], 'SizeData', 7); % Make dots smaller
xlim([0 2]); % Set x-axis limits
ylabel('A647 Pairwise Distance');
text('Position', [0.95, 0.95], 'String', sprintf('n = %d\nMedian: %.4f', numel(mean_a647_pdist), nanmedian(mean_a647_pdist)), ...
    'Units', 'normalized', 'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontSize', 10, 'FontWeight', 'bold');
hold on;
yline(nanmedian(mean_a647_pdist), 'r--', 'Median', 'LabelHorizontalAlignment', 'left'); % Add median line
hold off;

subplot(3, 2, 3);
scatter(0.8 + 0.4 * rand(size(a594_inter_centroid_dist)), a594_inter_centroid_dist, 'filled', 'MarkerFaceColor', [0.7 0.7 0.7], 'SizeData', 7); % Make dots smaller
xlim([0 2]); % Set x-axis limits
ylabel('A594 Inter-Centroid Distance');
text('Position', [0.95, 0.95], 'String', sprintf('n = %d\nMedian: %.4f', numel(a594_inter_centroid_dist), nanmedian(a594_inter_centroid_dist)), ...
    'Units', 'normalized', 'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontSize', 10, 'FontWeight', 'bold');
hold on;
yline(nanmedian(a594_inter_centroid_dist), 'r--', 'Median', 'LabelHorizontalAlignment', 'left'); % Add median line
hold off;

subplot(3, 2, 4);
scatter(0.8 + 0.4 * rand(size(a647_inter_centroid_dist)), a647_inter_centroid_dist, 'filled', 'MarkerFaceColor', [0.7 0.7 0.7], 'SizeData', 7); % Make dots smaller
xlim([0 2]); % Set x-axis limits
ylabel('A647 Inter-Centroid Distance');
text('Position', [0.95, 0.95], 'String', sprintf('n = %d\nMedian: %.4f', numel(a647_inter_centroid_dist), nanmedian(a647_inter_centroid_dist)), ...
    'Units', 'normalized', 'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontSize', 10, 'FontWeight', 'bold');
hold on;
yline(nanmedian(a647_inter_centroid_dist), 'r--', 'Median', 'LabelHorizontalAlignment', 'left'); % Add median line
hold off;

subplot(3, 2, 5);
scatter(0.8 + 0.4 * rand(size(min_a594_a647_inter_centroid_dist)), min_a594_a647_inter_centroid_dist, 'filled', 'MarkerFaceColor', [0.7 0.7 0.7], 'SizeData', 7); % Make dots smaller
xlim([0 2]); % Set x-axis limits
ylabel('Min A647-A594 Inter-Centroid Distance');
text('Position', [0.95, 0.95], 'String', sprintf('n = %d\nMedian: %.4f', numel(min_a594_a647_inter_centroid_dist), nanmedian(min_a594_a647_inter_centroid_dist)), ...
    'Units', 'normalized', 'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontSize', 10, 'FontWeight', 'bold');
hold on;
yline(nanmedian(min_a594_a647_inter_centroid_dist), 'r--', 'Median', 'LabelHorizontalAlignment', 'left'); % Add median line
hold off;

% Plot all intra-cluster pairwise distances as overlapping probability curves
figure(2);
hold on;
if ~isempty(all_a594_intra_clust_pdist)
    [f_a594, x_a594] = ksdensity(all_a594_intra_clust_pdist);
    plot(x_a594, f_a594, 'LineWidth', 2, 'Color', 'b'); % Use blue for A594
    text(max(x_a594), max(f_a594), sprintf('n = %d', numel(all_a594_intra_clust_pdist)), 'Color', 'b', 'FontSize', 10, 'VerticalAlignment', 'bottom', 'HorizontalAlignment', 'right');
end
if ~isempty(all_a647_intra_clust_pdist)
    [f_a647, x_a647] = ksdensity(all_a647_intra_clust_pdist);
    plot(x_a647, f_a647, 'LineWidth', 2, 'Color', 'r'); % Use red for A647
    text(max(x_a647), max(f_a647), sprintf('n = %d', numel(all_a647_intra_clust_pdist)), 'Color', 'r', 'FontSize', 10, 'VerticalAlignment', 'bottom', 'HorizontalAlignment', 'right');
end
xlabel('Pairwise Distance');
ylabel('Probability Density');
title('Intra-Cluster Pairwise Distance Probability Curves');
legend({'A594', 'A647'}, 'Location', 'Best');
hold off;

% Save figures as PDF
print(figure(1), fullfile(store_figs_dir, [dataset_name, '__intra_inter_cluster_distances']), '-dpdf');  % Save figure 1 as PDF
print(figure(2), fullfile(store_figs_dir, [dataset_name, '__intra_cluster_pairwise_densities']), '-dpdf');  % Save figure 2 as PDF