clc
%A script to parse FOLD-FISH data generated by Xiaoze Li
%Wang and pre-processed by Erik Wernersson
%
%Written by Nicola Crosetto in Sep-Nov 2025

%[]{}

cd('/Users/nicola.crosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/Analyses/Image analyses')

%% Parse all datasets except Chr17-spotting and count segmented nuclei

clear all

%Load data
source_data_dir = '/Users/nicola.crosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/Analyses/Image analyses/Source datasets/Segmented nuclei';
files = dir([source_data_dir,'/*.csv']);

%Specify folder where parsed data should be stored
store_data_dir = '/Users/nicola.crosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/Analyses/Image analyses/Parsed datasets';

%Loop through each dataset
for k=1:numel(files)

    % Extract dataset ID
    file_name = files(k).name;
    idx = strfind(file_name, '_'); %Find index of underscores
    if numel(idx) >= 2
        dataset_id{k,1} = file_name(idx(1)+1 : idx(2)-1); %Extract dataset ID
    else
        dataset_id{k,1} = ''; % Handle case where there are not enough underscores
    end

    % Open each dataset and count # of nuclei segmented and extract each
    % nucleus area
    data = readtable(fullfile(source_data_dir, file_name));
    all_seg_nuc_num(k, 1) = height(data);
    all_seg_nuc_area{k, 1} = data.Area_um;

end

% Store results in a structured array for saving
all_seg_nuc.dataset = dataset_id;
all_seg_nuc.counts = all_seg_nuc_num;
all_seg_nuc.area = all_seg_nuc_area;


% Save the structured data to a .mat file
save(fullfile(store_data_dir, 'all_seg_nuc_data.mat'), 'all_seg_nuc');

% clear all
% clc


%% Parse all datasets except Chr17-spotting and count dots per nucleus

clear all

%Load data
source_data_dir = '/Users/nicola.crosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/Analyses/Image analyses/Source datasets/Dot tables';
files = dir([source_data_dir,'/*.tsv']);

%Specify folder where parsed data should be stored
store_data_dir = '/Users/nicola.crosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/Analyses/Image analyses/Parsed datasets';

%Loop through each dataset
for k=1:numel(files)
    
    data = readtable([source_data_dir,'/',files(k).name],'FileType','text');

    %Count # of dots per nucleus in segmented nuclei
    fov_num = max(data.fov); %Number of FOVs in dataset
    seg_nuc_counter = 1; %Counter of segmented nuclei with size [25,100] um2

    %Loop through each FOV and nucleus, count dots and extract dot coord
    for i=1:fov_num 
        
        seg_nuc_in_fov_id = unique(data.nuc_id(data.fov==i & data.nuc_id>0)); %ID of segmented nuclei in FOV
        seg_nuc_in_fov_num = numel(seg_nuc_in_fov_id); %Number of segmented nuclei in FOV
        seg_nuc_in_fov_dot_coord{i,1}=[]; %Array to store dot coord in each segmented nucleus by FOV

        %Loop through segmented nuclei in FOV
        for j=1:seg_nuc_in_fov_num
            
            %Count dots in j-th nucleus
            seg_nuc_dot_num(seg_nuc_counter,1) = sum(data.nuc_id(data.fov==i)==seg_nuc_in_fov_id(j));
            mean_seg_nuc_dot_contrast(seg_nuc_counter, 1) = mean(data.Contrast(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j)));
            seg_nuc_counter = seg_nuc_counter + 1;
            
            %Extract coord of dots in j-th nucleus
            dot_coord_in_seg_nuc = horzcat(data.x(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j)),...
                                           data.y(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j)),...
                                           data.z(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j)));
            seg_nuc_in_fov_dot_coord{i,1} = vertcat(seg_nuc_in_fov_dot_coord{i},dot_coord_in_seg_nuc);

        end

    end

    % Store results in a table
    seg_nuc_data.dot_counts = seg_nuc_dot_num;
    seg_nuc_data.mean_contrast = mean_seg_nuc_dot_contrast;
    seg_nuc_data.dot_coord = seg_nuc_in_fov_dot_coord;

    % Save the structured data to a .mat file
    baseFileName = erase(files(k).name, '.tsv');    % Remove .tsv from file name for saving figures
    save(fullfile(store_data_dir, [baseFileName,'__seg_nuc_data.mat']), 'seg_nuc_data');

    clear seg_nuc_data data seg_nuc_dot_num mean_seg_nuc_dot_contrast dot_coord_in_seg_nuc seg_nuc_in_fov_dot_coord

end

clear all
clc


%% Parse chr17-spotting iiXZ1126 dataset and extract dot coord in each cluster

clear all

%Specify dataset to analyse
dataset_name = 'iiXZ1126_20250210_002_dw_A594_A647_cwdots_clusters_20251013.tsv';

%Specify folder where parsed data should be stored
store_data_dir = '/Users/nicola.crosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/Analyses/Image analyses/Parsed datasets';

%Load data
source_data_dir = '/Users/nicola.crosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/Analyses/Image analyses/Source datasets/Chr17 territories';
data = readtable([source_data_dir,'/',dataset_name],'FileType','text');

%Count # of dots per nucleus in segmented nuclei
fov_num = max(data.fov); %Number of FOVs in dataset
seg_nuc_counter = 1; %Counter of segmented nuclei with size [25,100] um2

a594_seg_nuc_id = []; %Matrix to store the seg_nuc_counter value corresponding to each dot
a594_seg_nuc_dot_coord = []; %Matrix to store A594 dot coord of each segmented nucleus
a594_seg_nuc_clust_id = []; %Matrix to store the cluster_id of each A594 dot in each segmented nucleus

a647_seg_nuc_id = []; %Matrix to store the seg_nuc_counter value corresponding to each dot
a647_seg_nuc_dot_coord = []; %Matrix to store A647 dot coord of each segmented nucleus
a647_seg_nuc_clust_id = []; %Matrix to store the cluster_id of each A647 dot in each segmented nucleus


%Loop through each FOV and nucleus, count dots, extract dot coord and cluster ID
for i=1:fov_num

    seg_nuc_in_fov_id = unique(data.nuc_id(data.fov==i & data.nuc_id>0)); %ID of segmented nuclei in FOV
    seg_nuc_in_fov_num = numel(seg_nuc_in_fov_id); %Number of segmented nuclei in FOV

    %Loop through segmented nuclei in FOV
    for j=1:seg_nuc_in_fov_num

        %Count dots in each channel in j-th nucleus
        a594_seg_nuc_dot_num(seg_nuc_counter,1) = sum(data.nuc_id(data.fov==i & strcmp(data.channel, 'A594')==1) == seg_nuc_in_fov_id(j) );
        a594_mean_seg_nuc_dot_contrast(seg_nuc_counter, 1) = mean(data.Contrast(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j) & strcmp(data.channel, 'A594')));

        a647_seg_nuc_dot_num(seg_nuc_counter,1) = sum(data.nuc_id(data.fov==i & strcmp(data.channel, 'A647')==1) == seg_nuc_in_fov_id(j));
        a647_mean_seg_nuc_dot_contrast(seg_nuc_counter, 1) = mean(data.Contrast(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j) & strcmp(data.channel, 'A647')));


        %Extract coord of dots in each channel in j-th nucleus and convert them to um (dx, dy = 65 nm, dz=200 nm)
        a594_x_coord_um =  data.f_x(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j) & strcmp(data.channel, 'A594')==1) * 0.065;
        a594_y_coord_um =  data.f_y(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j) & strcmp(data.channel, 'A594')==1) * 0.065;
        a594_z_coord_um =  data.f_z(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j) & strcmp(data.channel, 'A594')==1) * 0.2;
        a594_dot_coord_in_seg_nuc = horzcat(a594_x_coord_um, a594_y_coord_um, a594_z_coord_um);
        a594_seg_nuc_dot_coord = vertcat(a594_seg_nuc_dot_coord, a594_dot_coord_in_seg_nuc);

        a647_x_coord_um =  data.f_x(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j) & strcmp(data.channel, 'A647')==1) * 0.065;
        a647_y_coord_um =  data.f_y(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j) & strcmp(data.channel, 'A647')==1) * 0.065;
        a647_z_coord_um =  data.f_z(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j) & strcmp(data.channel, 'A647')==1) * 0.2;
        a647_dot_coord_in_seg_nuc = horzcat(a647_x_coord_um, a647_y_coord_um, a647_z_coord_um);
        a647_seg_nuc_dot_coord = vertcat(a647_seg_nuc_dot_coord, a647_dot_coord_in_seg_nuc);


        %Extract cluster ID of dots in each channel in j-th nucleus
        a594_clust_id_in_seg_nuc = data.cluster_id(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j) & strcmp(data.channel, 'A594')==1);
        a594_seg_nuc_clust_id = vertcat(a594_seg_nuc_clust_id, a594_clust_id_in_seg_nuc);
        
        a647_clust_id_in_seg_nuc = data.cluster_id(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j) & strcmp(data.channel, 'A647')==1);
        a647_seg_nuc_clust_id = vertcat(a647_seg_nuc_clust_id, a647_clust_id_in_seg_nuc);


        %Assign nucleus ID to the newly added dots and cluster_id values
        a594_seg_nuc_id = vertcat(a594_seg_nuc_id,repmat(seg_nuc_counter,a594_seg_nuc_dot_num(seg_nuc_counter,1),1));
        a647_seg_nuc_id = vertcat(a647_seg_nuc_id,repmat(seg_nuc_counter,a647_seg_nuc_dot_num(seg_nuc_counter,1),1));

        seg_nuc_counter = seg_nuc_counter + 1;

    end

end

% Store results in a table
seg_nuc_data.a594_dot_counts = a594_seg_nuc_dot_num;
seg_nuc_data.a594_mean_contrast = a594_mean_seg_nuc_dot_contrast;
seg_nuc_data.a594_dot_coord = a594_seg_nuc_dot_coord;
seg_nuc_data.a594_cluster_id = a594_seg_nuc_clust_id;
seg_nuc_data.a594_nuc_id = a594_seg_nuc_id;

seg_nuc_data.a647_dot_counts = a647_seg_nuc_dot_num;
seg_nuc_data.a647_mean_contrast = a647_mean_seg_nuc_dot_contrast;
seg_nuc_data.a647_dot_coord = a647_seg_nuc_dot_coord;
seg_nuc_data.a647_cluster_id = a647_seg_nuc_clust_id;
seg_nuc_data.a647_nuc_id = a647_seg_nuc_id;

seg_nuc_data.seg_nuc_num = seg_nuc_counter - 1;


% Save the structured data to .mat files
baseFileName = erase(dataset_name, '.tsv');    % Remove .tsv from file name for saving figures
save(fullfile(store_data_dir, [baseFileName,'__seg_nuc_data.mat']), 'seg_nuc_data');

clear seg_nuc_data a647_seg_nuc_data data a594_seg_nuc_dot_num a594_mean_seg_nuc_dot_contrast ...
    a594_seg_nuc_dot_coord a594_seg_nuc_clust_id a594_seg_nuc_id a647_seg_nuc_dot_num ...
    a647_mean_seg_nuc_dot_contrast a647_seg_nuc_dot_coord a647_seg_nuc_clust_id a647_seg_nuc_id

clear all
clc


%% Parse chr17-spotting iiXZ1081 dataset and extract dot coord in each cluster

clear all

%Specify dataset to analyse
dataset_name = 'iiXZ1081_20241128_002_dw_A594_cwdots_clusters_20251022.tsv';

%Specify folder where parsed data should be stored
store_data_dir = '/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/Analyses/Image analyses/Parsed datasets';

%Load data
source_data_dir = '/Users/nicolacrosetto/Library/CloudStorage/OneDrive-KarolinskaInstitutet/KI/Manuscripts/Li Wang et al_FOLD-FISH/Analyses/Image analyses/Source datasets/Chr17 territories';
data = readtable([source_data_dir,'/',dataset_name],'FileType','text');

%Count # of dots per nucleus in segmented nuclei
fov_num = max(data.fov); %Number of FOVs in dataset
seg_nuc_counter = 1; %Counter of segmented nuclei with size [25,100] um2

seg_nuc_id = []; %Matrix to store the seg_nuc_counter value corresponding to each dot
seg_nuc_dot_coord = []; %Matrix to store dot coord of each segmented nucleus
seg_nuc_clust_id = []; %Matrix to store the cluster_id of each dot in each segmented nucleus


%Loop through each FOV and nucleus, count dots, extract dot coord and cluster ID
for i=1:fov_num

    seg_nuc_in_fov_id = unique(data.nuc_id(data.fov==i & data.nuc_id>0)); %ID of segmented nuclei in FOV
    seg_nuc_in_fov_num = numel(seg_nuc_in_fov_id); %Number of segmented nuclei in FOV

    %Loop through segmented nuclei in FOV
    for j=1:seg_nuc_in_fov_num

        %Count dots in j-th nucleus
        seg_nuc_dot_num(seg_nuc_counter,1) = sum(data.nuc_id(data.fov==i) == seg_nuc_in_fov_id(j));
        mean_seg_nuc_dot_contrast(seg_nuc_counter, 1) = mean(data.Contrast(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j)));

        %Extract coord of dots in j-th nucleus and convert them to um (dx, dy = 65 nm, dz=200 nm)
        x_coord_um =  data.f_x(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j)) * 0.065;
        y_coord_um =  data.f_y(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j)) * 0.065;
        z_coord_um =  data.f_z(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j)) * 0.2;
        dot_coord_in_seg_nuc = horzcat(x_coord_um, y_coord_um, z_coord_um);
        seg_nuc_dot_coord = vertcat(seg_nuc_dot_coord, dot_coord_in_seg_nuc);

        %Extract cluster ID of dots in j-th nucleus
        clust_id_in_seg_nuc = data.cluster_id(data.fov==i & data.nuc_id==seg_nuc_in_fov_id(j));
        seg_nuc_clust_id = vertcat(seg_nuc_clust_id, clust_id_in_seg_nuc);

        %Assign nucleus ID to the newly added dots and cluster_id values
        seg_nuc_id = vertcat(seg_nuc_id,repmat(seg_nuc_counter,seg_nuc_dot_num(seg_nuc_counter,1),1));

        seg_nuc_counter = seg_nuc_counter + 1;

    end

end

% Store results in a table
seg_nuc_data.dot_counts = seg_nuc_dot_num;
seg_nuc_data.mean_contrast = mean_seg_nuc_dot_contrast;
seg_nuc_data.dot_coord = seg_nuc_dot_coord;
seg_nuc_data.cluster_id = seg_nuc_clust_id;
seg_nuc_data.nuc_id = seg_nuc_id;

seg_nuc_data.seg_nuc_num = seg_nuc_counter - 1;


% Save the structured data to .mat files
baseFileName = erase(dataset_name, '.tsv');    % Remove .tsv from file name for saving figures
save(fullfile(store_data_dir, [baseFileName,'__seg_nuc_data.mat']), 'seg_nuc_data');

clear seg_nuc_data data seg_nuc_dot_num mean_seg_nuc_dot_contrast ...
    seg_nuc_dot_coord seg_nuc_clust_id seg_nuc_id

clear all
clc
